// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evarrpc.proto

package com.eastelsoft.etos2.rpc.serialize.protobuf;

public final class Evarrpc {
  private Evarrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string seq = 1;</code>
     */
    java.lang.String getSeq();
    /**
     * <code>string seq = 1;</code>
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <code>string interfaceName = 2;</code>
     */
    java.lang.String getInterfaceName();
    /**
     * <code>string interfaceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>string method = 3;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>repeated bytes params = 4;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getParamsList();
    /**
     * <code>repeated bytes params = 4;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated bytes params = 4;</code>
     */
    com.google.protobuf.ByteString getParams(int index);
  }
  /**
   * Protobuf type {@code com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest}
   */
  public  static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      seq_ = "";
      interfaceName_ = "";
      method_ = "";
      params_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              seq_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              interfaceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                params_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              params_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = java.util.Collections.unmodifiableList(params_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.class, com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SEQ_FIELD_NUMBER = 1;
    private volatile java.lang.Object seq_;
    /**
     * <code>string seq = 1;</code>
     */
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <code>string seq = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object interfaceName_;
    /**
     * <code>string interfaceName = 2;</code>
     */
    public java.lang.String getInterfaceName() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <code>string interfaceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 3;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> params_;
    /**
     * <code>repeated bytes params = 4;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated bytes params = 4;</code>
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated bytes params = 4;</code>
     */
    public com.google.protobuf.ByteString getParams(int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSeqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seq_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceName_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeBytes(4, params_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSeqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seq_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceName_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(params_.get(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest)) {
        return super.equals(obj);
      }
      com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest other = (com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest) obj;

      boolean result = true;
      result = result && getSeq()
          .equals(other.getSeq());
      result = result && getInterfaceName()
          .equals(other.getInterfaceName());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && getParamsList()
          .equals(other.getParamsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest)
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.class, com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.Builder.class);
      }

      // Construct using com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seq_ = "";

        interfaceName_ = "";

        method_ = "";

        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor;
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest getDefaultInstanceForType() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.getDefaultInstance();
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest build() {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest buildPartial() {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest result = new com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.seq_ = seq_;
        result.interfaceName_ = interfaceName_;
        result.method_ = method_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = java.util.Collections.unmodifiableList(params_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest) {
          return mergeFrom((com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest other) {
        if (other == com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest.getDefaultInstance()) return this;
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          onChanged();
        }
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object seq_ = "";
      /**
       * <code>string seq = 1;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string seq = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceName_ = "";
      /**
       * <code>string interfaceName = 2;</code>
       */
      public java.lang.String getInterfaceName() {
        java.lang.Object ref = interfaceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        java.lang.Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder setInterfaceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder clearInterfaceName() {
        
        interfaceName_ = getDefaultInstance().getInterfaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 3;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> params_ = java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          params_ = new java.util.ArrayList<com.google.protobuf.ByteString>(params_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getParamsList() {
        return java.util.Collections.unmodifiableList(params_);
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public com.google.protobuf.ByteString getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public Builder setParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public Builder addParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes params = 4;</code>
       */
      public Builder clearParams() {
        params_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcRequest)
    private static final com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest();
    }

    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string seq = 1;</code>
     */
    java.lang.String getSeq();
    /**
     * <code>string seq = 1;</code>
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <code>string interfaceName = 2;</code>
     */
    java.lang.String getInterfaceName();
    /**
     * <code>string interfaceName = 2;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceNameBytes();

    /**
     * <code>string method = 3;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>string ecode = 4;</code>
     */
    java.lang.String getEcode();
    /**
     * <code>string ecode = 4;</code>
     */
    com.google.protobuf.ByteString
        getEcodeBytes();

    /**
     * <code>string emsg = 5;</code>
     */
    java.lang.String getEmsg();
    /**
     * <code>string emsg = 5;</code>
     */
    com.google.protobuf.ByteString
        getEmsgBytes();

    /**
     * <code>bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse}
   */
  public  static final class RpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse)
      RpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResponse() {
      seq_ = "";
      interfaceName_ = "";
      method_ = "";
      ecode_ = "";
      emsg_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              seq_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              interfaceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ecode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              emsg_ = s;
              break;
            }
            case 50: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.class, com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private volatile java.lang.Object seq_;
    /**
     * <code>string seq = 1;</code>
     */
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <code>string seq = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object interfaceName_;
    /**
     * <code>string interfaceName = 2;</code>
     */
    public java.lang.String getInterfaceName() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceName_ = s;
        return s;
      }
    }
    /**
     * <code>string interfaceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
      java.lang.Object ref = interfaceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 3;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ECODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object ecode_;
    /**
     * <code>string ecode = 4;</code>
     */
    public java.lang.String getEcode() {
      java.lang.Object ref = ecode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ecode_ = s;
        return s;
      }
    }
    /**
     * <code>string ecode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEcodeBytes() {
      java.lang.Object ref = ecode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ecode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMSG_FIELD_NUMBER = 5;
    private volatile java.lang.Object emsg_;
    /**
     * <code>string emsg = 5;</code>
     */
    public java.lang.String getEmsg() {
      java.lang.Object ref = emsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emsg_ = s;
        return s;
      }
    }
    /**
     * <code>string emsg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEmsgBytes() {
      java.lang.Object ref = emsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSeqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seq_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceName_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
      }
      if (!getEcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ecode_);
      }
      if (!getEmsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, emsg_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(6, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSeqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seq_);
      }
      if (!getInterfaceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceName_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
      }
      if (!getEcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ecode_);
      }
      if (!getEmsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, emsg_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse)) {
        return super.equals(obj);
      }
      com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse other = (com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse) obj;

      boolean result = true;
      result = result && getSeq()
          .equals(other.getSeq());
      result = result && getInterfaceName()
          .equals(other.getInterfaceName());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && getEcode()
          .equals(other.getEcode());
      result = result && getEmsg()
          .equals(other.getEmsg());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceName().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + ECODE_FIELD_NUMBER;
      hash = (53 * hash) + getEcode().hashCode();
      hash = (37 * hash) + EMSG_FIELD_NUMBER;
      hash = (53 * hash) + getEmsg().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse)
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.class, com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.Builder.class);
      }

      // Construct using com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seq_ = "";

        interfaceName_ = "";

        method_ = "";

        ecode_ = "";

        emsg_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor;
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse getDefaultInstanceForType() {
        return com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.getDefaultInstance();
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse build() {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse buildPartial() {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse result = new com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse(this);
        result.seq_ = seq_;
        result.interfaceName_ = interfaceName_;
        result.method_ = method_;
        result.ecode_ = ecode_;
        result.emsg_ = emsg_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse) {
          return mergeFrom((com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse other) {
        if (other == com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse.getDefaultInstance()) return this;
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          onChanged();
        }
        if (!other.getInterfaceName().isEmpty()) {
          interfaceName_ = other.interfaceName_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.getEcode().isEmpty()) {
          ecode_ = other.ecode_;
          onChanged();
        }
        if (!other.getEmsg().isEmpty()) {
          emsg_ = other.emsg_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object seq_ = "";
      /**
       * <code>string seq = 1;</code>
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string seq = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder clearSeq() {
        
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 1;</code>
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seq_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceName_ = "";
      /**
       * <code>string interfaceName = 2;</code>
       */
      public java.lang.String getInterfaceName() {
        java.lang.Object ref = interfaceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceNameBytes() {
        java.lang.Object ref = interfaceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder setInterfaceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder clearInterfaceName() {
        
        interfaceName_ = getDefaultInstance().getInterfaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceName = 2;</code>
       */
      public Builder setInterfaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 3;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 3;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ecode_ = "";
      /**
       * <code>string ecode = 4;</code>
       */
      public java.lang.String getEcode() {
        java.lang.Object ref = ecode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ecode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ecode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEcodeBytes() {
        java.lang.Object ref = ecode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ecode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ecode = 4;</code>
       */
      public Builder setEcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ecode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ecode = 4;</code>
       */
      public Builder clearEcode() {
        
        ecode_ = getDefaultInstance().getEcode();
        onChanged();
        return this;
      }
      /**
       * <code>string ecode = 4;</code>
       */
      public Builder setEcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ecode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emsg_ = "";
      /**
       * <code>string emsg = 5;</code>
       */
      public java.lang.String getEmsg() {
        java.lang.Object ref = emsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emsg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEmsgBytes() {
        java.lang.Object ref = emsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emsg = 5;</code>
       */
      public Builder setEmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emsg = 5;</code>
       */
      public Builder clearEmsg() {
        
        emsg_ = getDefaultInstance().getEmsg();
        onChanged();
        return this;
      }
      /**
       * <code>string emsg = 5;</code>
       */
      public Builder setEmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emsg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 6;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse)
    }

    // @@protoc_insertion_point(class_scope:com.eastelsoft.etos2.rpc.serialize.protobuf.RpcResponse)
    private static final com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse();
    }

    public static com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    public com.eastelsoft.etos2.rpc.serialize.protobuf.Evarrpc.RpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\revarrpc.proto\022+com.eastelsoft.etos2.rp" +
      "c.serialize.protobuf\"P\n\nRpcRequest\022\013\n\003se" +
      "q\030\001 \001(\t\022\025\n\rinterfaceName\030\002 \001(\t\022\016\n\006method" +
      "\030\003 \001(\t\022\016\n\006params\030\004 \003(\014\"l\n\013RpcResponse\022\013\n" +
      "\003seq\030\001 \001(\t\022\025\n\rinterfaceName\030\002 \001(\t\022\016\n\006met" +
      "hod\030\003 \001(\t\022\r\n\005ecode\030\004 \001(\t\022\014\n\004emsg\030\005 \001(\t\022\014" +
      "\n\004data\030\006 \001(\014B-\n+com.eastelsoft.etos2.rpc" +
      ".serialize.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcRequest_descriptor,
        new java.lang.String[] { "Seq", "InterfaceName", "Method", "Params", });
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_eastelsoft_etos2_rpc_serialize_protobuf_RpcResponse_descriptor,
        new java.lang.String[] { "Seq", "InterfaceName", "Method", "Ecode", "Emsg", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
